import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footar from "@/components/footar/Footar";
import { Cairo } from "next/font/google";

const cairo = Cairo({
  subsets: ["arabic", "latin"],
  weight: ["400", "500", "700"], // الأوزان اللي محتاجها
  variable: "--font-cairo",      // هنعرفه كـ CSS variable
});

export const metadata = {
  title: "ميدان التخزين",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl" className={cairo.variable}>
      <body className="font-sans antialiased">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
